{% set name = "multiprocess" %}
{% set version = "0.70.12.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 206bb9b97b73f87fec1ed15a19f8762950256aa84225450abc7150d02855a083

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=0.6
    - dill >=0.2.5
  run:
    - python
    - dill >=0.2.5

test:
  imports:
    - multiprocess
    - multiprocess.dummy

about:
  home: https://pypi.org/project/multiprocess/
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: better multiprocessing and multithreading in python
  dev_url: https://github.com/uqfoundation/multiprocess

extra:
  recipe-maintainers:
    - jschueller
