{% set version = "0.70.18" %}

package:
  name: multiprocess
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multiprocess/multiprocess-{{ version }}.tar.gz
  sha256: f9597128e6b3e67b23956da07cf3d2e5cba79e2f4e0fba8d7903636663ec6d0d
  patches:
    - 0001-add-packaging.patch
    - 0002-unpin-py313.patch

build:
  skip: true  # [py<38]
  number: 0
  script:
    # Temp fix:
    # Upstream included the wrong tag in the setup.cfg
    # during the source upload. This deletes it to allow it to be regenerated
    # https://github.com/uqfoundation/multiprocess/pull/197
    - rm setup.cfg    # [unix]
    - del setup.cfg   # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools >=42
    - dill >=0.3.9
    - packaging
  run:
    - python
    - dill >=0.3.9

test:
  requires:
    - pip
  imports:
    - multiprocess
    - multiprocess.dummy
  commands:
    # pip check is currently broken due to bad upstream metadata
    - pip check

about:
  home: https://github.com/uqfoundation/multiprocess
  license: BSD-3-Clause
  license_file: COPYING
  summary: better multiprocessing and multithreading in python
  doc_url: https://multiprocess.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
    - thewchan
