{% set name = "multiprocess" %}
{% set version = "0.70.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 9d5e417f3ebce4d027a3c900995840f167f316d9f73c0a7a1fbb4ac0116298d0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=0.6
    - dill >=0.2.5
  run:
    - python
    - dill >=0.2.5

test:
  imports:
    - multiprocess
    - multiprocess.dummy

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: better multiprocessing and multithreading in python

extra:
  recipe-maintainers:
    - jschueller
