{% set version = "0.70.17" %}

package:
  name: multiprocess
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multiprocess/multiprocess-{{ version }}.tar.gz
  sha256: 4ae2f11a3416809ebc9a48abfc8b14ecce0652a0944731a1493a3c1ba44ff57a

build:
  skip: True  # [py<38]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools >=42
    - dill >=0.3.9
  run:
    - python
    - dill >=0.3.9

test:
  requires:
    - pip
  imports:
    - multiprocess
    - multiprocess.dummy
  commands:
    # pip check is currently broken due to bad upstream metadata
    - pip check

about:
  home: https://pypi.org/project/multiprocess/
  license: BSD-3-Clause
  license_file: COPYING
  summary: better multiprocessing and multithreading in python
  dev_url: https://github.com/uqfoundation/multiprocess

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
    - thewchan
