{% set version = "0.70.16" %}

package:
  name: multiprocess
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multiprocess/multiprocess-{{ version }}.tar.gz
  sha256: 161af703d4652a0e1410be6abccecde4a7ddffd19341be0a7011b94aeb171ac1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - dill >=0.3.6
  run:
    - python
    - dill >=0.3.6

test:
  requires:
    - pip
  imports:
    - multiprocess
    - multiprocess.dummy
  commands:
    - pip check

about:
  home: https://pypi.org/project/multiprocess/
  license: BSD-3-Clause
  license_file: COPYING
  summary: better multiprocessing and multithreading in python
  dev_url: https://github.com/uqfoundation/multiprocess

extra:
  recipe-maintainers:
    - jschueller
