schema_version: 1

context:
  version: 0.70.16

package:
  name: multiprocess
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/multiprocess/multiprocess-${{ version }}.tar.gz
  sha256: 161af703d4652a0e1410be6abccecde4a7ddffd19341be0a7011b94aeb171ac1
  patches:
    - 0001-add-packaging.patch
    - 0002-unpin-py313.patch

build:
  number: 2
  script:
    # Temp fix:
    # Upstream included the wrong tag in the setup.cfg
    # during the source upload. This deletes it to allow it to be regenerated
    # https://github.com/uqfoundation/multiprocess/pull/197
    - if: unix
      then: rm setup.cfg
    - if: win
      then: del setup.cfg
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools >=42
    - dill >=0.3.9
    - packaging
  run:
    - python
    - dill >=0.3.9

tests:
  - python:
      imports:
        - multiprocess
        - multiprocess.dummy
      pip_check: true

about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: better multiprocessing and multithreading in python
  homepage: https://github.com/uqfoundation/multiprocess
  documentation: https://multiprocess.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
    - thewchan
